session_name: playlist-fprint-api
start_directory: ./
windows:

- window_name: playlist-fprint-api
  layout: tiled
  shell_command_before:
    - 'source ~/srv/playlist-fprint-api/bin/activate'
  panes:
    - shell_command:
        - ./app/manage.py runserver 0.0.0.0:8080
    - cd app
    - cd app
    - cd app
