session_name: playlist-fprint-api
start_directory: ./
windows:

- window_name: fprint-api
  layout: tiled
  shell_command_before:
    - 'source ~/srv/fprint-api/bin/activate'
  panes:
    - shell_command:
        - ./manage.py runserver 0.0.0.0:7777
    - cd app
    - cd app
    - cd app
