version: '3'

services:
  db:
    volumes:
      - fprint_db:/data
    environment:
      PGDATA: /data
  web:
    volumes:
      - fprint_index:/index
    environment:
      PUBLIC_APP_URL: 'http://web:8000'
      INDEX_BASE_DIR: '/index'
